---
# Must gather host facts for all hosts so ifaces are defined.
- name: Gather facts.
  hosts: all
  tasks:
    - setup:

# This is a hack to get around the bizarre variable precedence for dependency roles.
# Since the ssl-generate-certificate role is a dependency of elk, play-level vars
# are ignored in the context of the ssl dependency role. Storing the vars in the elk
# role's vars directory resolves, but it's a messy solution.
- name: Configure var overrides for testing.
  hosts: logserver
  gather_facts: no
  vars:
    logserver_integration_tests_var_overrides:
      elk_configure_firewall: no
      ssl_certificate_ip_address: "{{ hostvars.logserver.ansible_eth1.ipv4.address }}"
  tasks:
    - name: Creates temporary vars dir in local elk role.
      local_action:
        module: file
        state: directory
        path: ./roles/freedomofpress.elk/vars

    - name: Write temporary vars file to local elk role.
      local_action:
        module: copy
        content: "{{ logserver_integration_tests_var_overrides|to_nice_yaml }}"
        dest: ./roles/freedomofpress.elk/vars/main.yml

- name: Stand up logserver.
  hosts: logserver
  roles:
    - role: freedomofpress.elk
      become: yes
      tags: elk

    - role: freedomofpress.riemann
      become: yes
      tags: riemann

- name: Configure logclients.
  hosts: logclients
  roles:
    - role: freedomofpress.logstash-client
      logstash_client_ssl_certificate: files/logstash-client.crt
      # For vagrant, must set eth1 as default interface.
      logstash_client_logserver_ip_address: "{{ hostvars[groups.logserver.0].ansible_eth1.ipv4.address }}"
      tags: clients
